language: php
git:
  submodules: false
notifications:
  email:
    recipients:
    - wordman05@gmail.com
    - nickpowers43@gmail.com
    on_success: change
    on_failure: change
branches:
  only:
  - master
addons:
  apt:
    packages:
    - nodejs
    - git
install:
- npm install -g bower
- bower install bootstrap
script:
- echo 'Testing not configured!'
  - sed 's/TRAVISCIBUILDNUMBER/'$TRAVIS_BUILD_NUMBER'/' index2.htm > index2.html
  - sed 's/TRAVISCIBUILDNUMBER/'$TRAVIS_BUILD_NUMBER'/' index.htm > index.html
on_success:
  - chmod +x build/deploy/aws.sh
  - build/deploy/aws.sh
