language: ruby
git:
  submodules: false
notifications:
  email:
    recipients:
      - wordman05@gmail.com
      - nickpowers43@gmail.com
    on_success: change
    on_failure: change
branches:
  only:
  - master
addons:
  apt:
    packages:
install:
  - bundle install
script:
  - echo 'Configuring JIT variables...'
  - chmod +x ./jit.sh
  - ./jit.sh
  # Begin testing
  - echo 'Beginning unit tests...'
  - rake main:default
deploy:
  provider: heroku
  api_key: "9951e24c-b489-48fe-8a60-b325e8d850dd"
  app: enigmatic-thicket-1799
