language: ruby
git:
  submodules: false
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/247b654f9115ce88324e
    on_success: always
    on_failure: always
    on_start: never
  email:
    recipients:
      - wordman05@gmail.com
      - nickpowers43@gmail.com
    on_success: change
    on_failure: change
branches:
  only:
  - master
addons:
  apt:
    packages:
install:
  - bundle install
script:
  - echo 'Configuring JIT variables...'
  - echo $TRAVIS_BUILD_NUMBER':'$TRAVIS_COMMIT > ./builddata.txt
  - head ./builddata.txt
  # Begin testing
  - echo 'Beginning unit tests...'
  #- phpunit "Tests/lib-versionTest"
  - echo 'Unit testing is not set up!'
deploy:
  provider: heroku
  api_key: "9951e24c-b489-48fe-8a60-b325e8d850dd"
  app: enigmatic-thicket-1799
  skip_cleanup: true
