language: php
git:
  submodules: false
notifications:
  email:
    recipients:
    - wordman05@gmail.com
    - nickpowers43@gmail.com
    on_success: change
    on_failure: change
branches:
  only:
  - master
addons:
  apt:
    packages:
      - nodejs
      - git
install:
- npm install -g bower
- bower install bootstrap
script:
#  - phpunit
  - echo 'Testing not configured!'
  - sed 's/TRAVISCIBUILDNUMBER/'$TRAVIS_BUILD_NUMBER'/' index2.html > index3.html
  # Prepare for deploy
  #- mkdir wb_deploy
  #- cp ./index.php ./wb_deploy/
  #- cp ./index2.php ./wb_deploy/
  #- cp ./.htaccess ./wb_deploy/
  #- cp ./.bowerrc ./wb_deploy/
  #- cp -avr src wb_deploy
  #- ls
