language: php
git:
  submodules: false
notifications:
  email:
    recipients:
    - wordman05@gmail.com
    - nickpowers43@gmail.com
    on_success: change
    on_failure: change
branches:
  only:
  - master
addons:
  apt:
    packages:
    - nodejs
    - git
install:
- npm install -g bower
- bower install bootstrap
script:
  - sed 's/null/'$TRAVIS_BUILD_NUMBER'/' version.php > lib_version.php
  - head ./lib_version.php
  # Begin testing
  - phpunit "Tests/lib-versionTest"
deploy:
  provider: heroku
  api_key: "9951e24c-b489-48fe-8a60-b325e8d850dd"
  app: enigmatic-thicket-1799
