language: php
git:
  submodules: false
notifications:
  email:
    recipients:
    - wordman05@gmail.com
    - nickpowers43@gmail.com
    on_success: change
    on_failure: always
branches:
  only:
  - master
addons:
  apt:
    packages:
      - nodejs
      - git
install:
- npm install -g bower
- bower install bootstrap
script:
#  - phpunit
  - echo 'Testing not configured!'
  # Prepare for deploy
  - mkdir wb_deploy
  - cp ./index.php ./wb_deploy/
  - cp ./index2.php ./wb_deploy/
  - cp ./.htaccess ./wb_deploy/
  - cp ./.bowerrc ./wb_deploy/
  - cp ./src ./wb_deploy
  - ls
deploy:
- provider: s3
  access_key_id: AKIAIZOP3PL7XL32RQWQ
  secret_access_key: &1
    secure: CUsV0bZgyM/J8AdTz6t5kcRbf+uKZoXoq6HdIJ6JhhuOr9IWSj16M9rrU1wCipRmpq+dLsHFpojEcx0IMrcoP6VW0GIxRvIzn/a42J4iDu9LUEYll5tD4yqaOQcsLQIbuxngOhnlvxiXjPdtef0i3ko9O9QFoYXpOBL70zAxsso=
  local_dir: wb_deploy
  skip_cleanup: true
  on: &2
    repo: ARMmaster17/otternonsense-official
  bucket: oni-us-east
#- provider: codedeploy
#  access_key_id: AKIAIZOP3PL7XL32RQWQ
#  secret_access_key: *1
#    secure: CUsV0bZgyM/J8AdTz6t5kcRbf+uKZoXoq6HdIJ6JhhuOr9IWSj16M9rrU1wCipRmpq+dLsHFpojEcx0IMrcoP6VW0GIxRvIzn/a42J4iDu9LUEYll5tD4yqaOQcsLQIbuxngOhnlvxiXjPdtef0i3ko9O9QFoYXpOBL70zAxsso=
#  bucket: oni-us-east
#  key: website
#  bundle_type: ''
#  application: otternonsense-official
#  deployment_group: DeploymentGroup
#  on: *2
