language: php
before-install:
  - sudo apt-get install nodejs
  - sudo apt-get install git
install:
  - npm install -g bower
  - bower install bootstrap
 #- bower install jquery
script: build/test/test.sh
after_success: build/deploy/aws.sh
git:
  submodules: false
notifications:
  email:
    recipients:
      - wordman05@gmail.com
    on_success: change
    on_failure: always
branches:
  only:
    - master
