language: php
before-install:
  - sudo apt-get install nodejs
install:
  - npm install -g bower
  - bower install bootstrap
  - bower install jquery
script: build/test/test.sh
deployment: build/deploy/aws.sh
git:
  submodules: false
notifications:
  email: false
branches:
  only:
    - master
